---
abstract: 'Git as versioned data store in Perl'
author:
  - 'Fayland Lam <fayland@gmail.com>'
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  FindBin: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::More: 0.94
  perl: 5.004
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: GitStore
provides:
  GitStore:
    file: lib/GitStore.pm
    version: 0.13
  GitStore::Revision:
    file: lib/GitStore/Revision.pm
    version: 0.13
requires:
  Carp: 0
  DateTime: 0
  Git::PurePerl: 0
  List::Util: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  Path::Class: 0
  Storable: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=GitStore
  homepage: http://search.cpan.org/dist/GitStore/
  repository: https://github.com/yanick/perl-git-store.git
version: 0.13
x_authority: cpan:YANICK
